name: athena-forecast
dependencies:
- python=3.7
- pandas<1.1
- jupyter
- matplotlib
- scikit-learn
- statsmodels
- seaborn
- pip
- pip:
  - gluonts==0.8.0
  - mxnet==1.6
  - xgboost
  - pytest
  - PyWavelets
  - pycwt

  
